subscribers:

  camera_reading:
    topic: /tb3_1/camera/rgb/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros1/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros1/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros1/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros1/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
